### PR TITLE
Fix pykeepass

### PR DESCRIPTION
**Pull request by cew-caroline**
Bump pykeepass from 3.2.1 to last version; replace deprecated function find_entries by find_entries_by_path;

### CODE REVIEW

**Comment by driouu** [comment]
I confirm that this PR is fixing usage with `ansible [core 2.11.8]`
(broken after update from `2.9.4`

**Comment by vaz-ar** [comment]
@viczem Do you have any plan to merge this PR ? Or is something missing / causing some problems, like the facts that the commit logs are in french ?

**Comment by viczem** [comment]
@vaz-ar @driouu @cew-caroline I will not merge this PR. Please see updated code with pykeepass>=4

**Comment by viczem** [comment]
@vaz-ar @driouu @cew-caroline I will not merge this PR. Please see updated code with pykeepass>=4

**Pull request closed without merging**
